on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: # 1. 코드 체크아웃
      - name: Check out code
        uses: actions/checkout@v4

      # 2. JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      # jq 설치
      - name: Install jq
        run: sudo apt-get install jq -y

      # 3. Gradle 의존성 캐시 설정
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. Gradle Wrapper 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 5. 빌드 및 테스트 실행
      - name: Build and Test
        run: ./gradlew build -x test

      # 6. Zip Layer 생성
      - name: Build ZipLayer
        run: ./gradlew zipLayer

      - name: 경로 확인
        run: ls /home/runner/work/FinalProject_5RE5_BE_WORKER/FinalProject_5RE5_BE_WORKER/build

      - name: AWS 로그인
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: layer 생성 and 추가
        run: |
          PUBLISH_OUTPUT=$(aws lambda publish-layer-version \
            --layer-name my-java-layer \
            --description "Java libraries for Lambda functions" \
            --zip-file fileb:///home/runner/work/FinalProject_5RE5_BE_WORKER/FinalProject_5RE5_BE_WORKER/build/my-java-layer.zip \
            --compatible-runtimes java17 \
            --region ${{ secrets.AWS_REGION }})

          LAYER_VERSION=$(echo $PUBLISH_OUTPUT | jq -r '.Version')
          LAYER_ARN="arn:aws:lambda:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:layer:my-java-layer:$LAYER_VERSION"

          echo "Layer Version: $LAYER_VERSION"
          
          echo "Layer 추가 실행"
          aws lambda update-function-configuration \
          --function-name ${{ secrets.LAMBDA_NAME }} \
          --layers arn:aws:lambda:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:layer:my-java-layer:$LAYER_VERSION
          

      - name: Deploy Function CODE
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_NAME }} \
            --zip-file fileb:///home/runner/work/FinalProject_5RE5_BE_WORKER/FinalProject_5RE5_BE_WORKER/build/libs/FinalProject_5RE5_BE_WORKER-1.0-SNAPSHOT.jar \
            --publish